X = "X"
O = "O"
BLANK = None

MINIMAX_TOP_VALUE = 10000
GRID_SIZE = 3
GAME_SIZE = GRID_SIZE * GRID_SIZE
WINDOW_SIZE = (500, 500)
MIN_WINDOW_SIZE = (300, 300)
AI_THINK_TIME = 1
SHOW_GAME_OVER_TIME = 1
